"""Deterministic node and graph tests using an LLM test double."""

from __future__ import annotations

from types import SimpleNamespace
from typing import Any

import pytest

import langgraph_agent_lab.nodes as nodes
from langgraph_agent_lab.graph import build_graph
from langgraph_agent_lab.persistence import build_checkpointer
from langgraph_agent_lab.state import Route, Scenario, initial_state


class FakeLLM:
    """Small provider double that preserves structured-output behavior."""

    def __init__(self) -> None:
        self.schema: type[Any] | None = None

    def with_structured_output(self, schema: type[Any]) -> FakeLLM:
        self.schema = schema
        return self

    def invoke(self, prompt: str) -> object:
        normalized = prompt.casefold()
        if self.schema is nodes.Classification:
            request = normalized.rsplit("user request:", maxsplit=1)[-1]
            if any(term in request for term in ("refund", "delete", "cancel")):
                route = "risky"
            elif any(term in request for term in ("lookup", "status", "track")):
                route = "tool"
            elif "can you fix it?" in request:
                route = "missing_info"
            elif any(term in request for term in ("timeout", "failure", "crash")):
                route = "error"
            else:
                route = "simple"
            return {"route": route, "reason": "fake structured classification"}
        if self.schema is nodes.ToolEvaluation:
            tool_result = normalized.rsplit("tool result:", maxsplit=1)[-1]
            verdict = "needs_retry" if "error:" in tool_result else "success"
            return {"verdict": verdict, "reason": "fake structured evaluation"}
        return SimpleNamespace(content="Grounded response generated by the fake chat model.")


@pytest.fixture(autouse=True)
def fake_llm(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(nodes, "get_llm", lambda **_kwargs: FakeLLM())


@pytest.mark.parametrize(
    ("query", "expected_route"),
    [
        ("How do I reset my password?", Route.SIMPLE),
        ("Please lookup order status for order 12345", Route.TOOL),
        ("Can you fix it?", Route.MISSING_INFO),
        ("Refund this customer", Route.RISKY),
        ("Timeout failure while processing", Route.ERROR),
    ],
)
def test_graph_routes_and_finalizes(query: str, expected_route: Route) -> None:
    scenario = Scenario(id=f"offline-{expected_route}", query=query, expected_route=expected_route)
    state = initial_state(scenario)
    graph = build_graph(build_checkpointer("memory"))

    result = graph.invoke(state, config={"configurable": {"thread_id": state["thread_id"]}})

    assert result["route"] == expected_route.value
    assert result.get("final_answer") or result.get("pending_question")
    assert result["events"][-1]["node"] == "finalize"


def test_retry_loop_eventually_succeeds() -> None:
    scenario = Scenario(
        id="retry-success",
        query="Timeout failure while processing",
        expected_route=Route.ERROR,
        max_attempts=3,
    )
    state = initial_state(scenario)
    result = build_graph(build_checkpointer("memory")).invoke(
        state,
        config={"configurable": {"thread_id": state["thread_id"]}},
    )

    visited = [event["node"] for event in result["events"]]
    assert result["attempt"] == 2
    assert visited.count("retry") == 2
    assert "dead_letter" not in visited


def test_retry_limit_routes_to_dead_letter() -> None:
    scenario = Scenario(
        id="dead-letter",
        query="System failure cannot recover",
        expected_route=Route.ERROR,
        max_attempts=1,
    )
    state = initial_state(scenario)
    result = build_graph(build_checkpointer("memory")).invoke(
        state,
        config={"configurable": {"thread_id": state["thread_id"]}},
    )

    visited = [event["node"] for event in result["events"]]
    assert "dead_letter" in visited
    assert visited[-1] == "finalize"


def test_tool_blocks_unapproved_risky_action() -> None:
    update = nodes.tool_node(
        {
            "route": Route.RISKY.value,
            "query": "Delete an account",
            "attempt": 0,
            "approval": None,
        }
    )
    assert str(update["tool_results"][0]).startswith("ERROR")
